server:
  port: 80
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

swagger:
  title: swagger配置测试
  description: swagger自动扫描测试
  license: GPLv3
  version: 0.01
  contactEmail: liangsiyuan@whutosa.com
  basePackagePath: io.github.wrobezin.framework
  pathRegex:
    hello: "^((?!hello).)*$"
